# DEV ONLY
SQL_DEV_CONNECTION: 127.0.0.1:3306

# Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
# Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
# For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
CLOUDSQL_CONNECTION_NAME: strengthdbinstance.c6edl7uupl3x.us-east-1.rds.amazonaws.com
CLOUDSQL_DATABASE: strength
# Replace username and password if you aren't using the root user.
CLOUDSQL_USER: rootuser
CLOUDSQL_PASSWORD: '!6rootuser'
#CORS OPTIONS
ORIGIN_ALLOWED: '*'
